use sea_orm_migration::prelude::*;
use sea_orm_migration::schema::{string, timestamp_with_time_zone, uuid};

#[derive(DeriveMigrationName)]
pub struct Migration;

/// Column names for this migration only. Migrations never import the entity
/// modules: entities are generated FROM the schema, so depending on them would
/// make old migrations break whenever the current schema moves on.
#[derive(DeriveIden)]
enum User {
    Table,
    Id,
    Email,
    Name,
    CreatedAt,
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(User::Table)
                    .if_not_exists()
                    // `auto_increment = false` on the entity side; the id is a
                    // uuid v7 generated by the application, not by Postgres.
                    .col(uuid(User::Id).primary_key())
                    .col(string(User::Email).unique_key())
                    .col(string(User::Name))
                    .col(
                        timestamp_with_time_zone(User::CreatedAt)
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(User::Table).to_owned())
            .await
    }
}
